repository:
  step:
    jar:
      - "https://repo1.maven.org/maven2/org/apache/camel/kamelets/camel-kamelets/0.4.0/camel-kamelets-0.4.0.jar"
  viewdefinition:
    jar:
      - "https://github.com/KaotoIO/kaoto-viewdefinition-catalog/archive/refs/tags/test.zip"

quarkus:
  http:
    test-port: 8083
    cors: true

