repository:
  step:
    jar:
      - "https://repo1.maven.org/maven2/org/apache/camel/kamelets/camel-kamelets/0.6.0/camel-kamelets-0.6.0.jar"
    git:
      -
        url: "https://github.com/KaotoIO/camel-component-metadata.git"
        tag: "main"
  viewdefinition:
    git:
      -
        url: "https://github.com/KaotoIO/kaoto-viewdefinition-catalog.git"
        tag: "main"

crd:
  default: "KameletBinding"

quarkus:
  http:
    test-port: 8083
    cors: true
  log:
    category:
      io.kaoto.backend.api:
        level: "TRACE"
      org.ecl.yas.int:
        level: "INFO"
